[package]
name = "bbcraft"
version = "0.1.0"
authors = ["RoccoDev <roccodev.business@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bit_utils = "0.1.1"
mc-varint = {git = "https://github.com/luojia65/mc-varint.git"}
rjni = {git = "https://github.com/benanders/rjni"}